-- 修复数据库表注释与字段注释中的乱码问号
SET NAMES utf8mb4;

ALTER TABLE `sys_user`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    MODIFY COLUMN `password` VARCHAR(100) NOT NULL COMMENT '密码（BCrypt）',
    MODIFY COLUMN `nickname` VARCHAR(50) DEFAULT NULL COMMENT '昵称',
    MODIFY COLUMN `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
    MODIFY COLUMN `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    MODIFY COLUMN `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-正常',
    MODIFY COLUMN `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
    MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='用户表';

ALTER TABLE `sys_role`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN `role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-正常',
    MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='角色表';

ALTER TABLE `sys_user_role`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN `role_id` BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='用户角色关联表';

ALTER TABLE `sys_menu`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父菜单ID，0 表示根节点',
    MODIFY COLUMN `menu_name` VARCHAR(100) NOT NULL COMMENT '菜单名称',
    MODIFY COLUMN `menu_type` TINYINT NOT NULL COMMENT '菜单类型：1-目录，2-菜单，3-按钮',
    MODIFY COLUMN `path` VARCHAR(255) DEFAULT NULL COMMENT '路由路径',
    MODIFY COLUMN `route_name` VARCHAR(100) DEFAULT NULL COMMENT '路由名称',
    MODIFY COLUMN `component` VARCHAR(255) DEFAULT NULL COMMENT '前端组件路径',
    MODIFY COLUMN `icon` VARCHAR(100) DEFAULT NULL COMMENT '图标',
    MODIFY COLUMN `permission_code` VARCHAR(100) DEFAULT NULL COMMENT '权限标识',
    MODIFY COLUMN `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN `visible` TINYINT NOT NULL DEFAULT 1 COMMENT '是否显示：0-隐藏，1-显示',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='菜单表';

ALTER TABLE `sys_role_menu`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `role_id` BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN `menu_id` BIGINT NOT NULL COMMENT '菜单ID',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='角色菜单关联表';

ALTER TABLE `trade_post`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `post_no` VARCHAR(32) NOT NULL COMMENT '发布单号',
    MODIFY COLUMN `publisher_id` BIGINT NOT NULL COMMENT '发布人ID',
    MODIFY COLUMN `post_type` TINYINT NOT NULL COMMENT '发布类型：1-需求，2-供给',
    MODIFY COLUMN `title` VARCHAR(100) NOT NULL COMMENT '标题',
    MODIFY COLUMN `content` TEXT COMMENT '详情描述',
    MODIFY COLUMN `price` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '预估价格',
    MODIFY COLUMN `city_name` VARCHAR(50) DEFAULT NULL COMMENT '城市名称',
    MODIFY COLUMN `area_name` VARCHAR(50) DEFAULT NULL COMMENT '区域名称',
    MODIFY COLUMN `address` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
    MODIFY COLUMN `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人',
    MODIFY COLUMN `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系电话',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-草稿，1-待审核，2-审核不通过，3-上架中，4-已下架',
    MODIFY COLUMN `reviewer_id` BIGINT DEFAULT NULL COMMENT '审核人ID',
    MODIFY COLUMN `review_time` DATETIME DEFAULT NULL COMMENT '审核时间',
    MODIFY COLUMN `review_remark` VARCHAR(255) DEFAULT NULL COMMENT '审核备注',
    MODIFY COLUMN `publish_time` DATETIME DEFAULT NULL COMMENT '上架时间',
    MODIFY COLUMN `off_shelf_time` DATETIME DEFAULT NULL COMMENT '下架时间',
    MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='发布主表';

ALTER TABLE `trade_post_image`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `post_id` BIGINT NOT NULL COMMENT '发布ID',
    MODIFY COLUMN `image_url` VARCHAR(255) NOT NULL COMMENT '图片地址',
    MODIFY COLUMN `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='发布图片表';

ALTER TABLE `trade_post_review`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `post_id` BIGINT NOT NULL COMMENT '发布ID',
    MODIFY COLUMN `reviewer_id` BIGINT NOT NULL COMMENT '审核人ID',
    MODIFY COLUMN `review_result` TINYINT NOT NULL COMMENT '审核结果：1-通过，2-不通过',
    MODIFY COLUMN `review_remark` VARCHAR(255) DEFAULT NULL COMMENT '审核说明',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='发布审核记录表';

ALTER TABLE `trade_order`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `order_no` VARCHAR(32) NOT NULL COMMENT '订单号',
    MODIFY COLUMN `post_id` BIGINT NOT NULL COMMENT '来源发布ID',
    MODIFY COLUMN `publisher_id` BIGINT NOT NULL COMMENT '发布方用户ID',
    MODIFY COLUMN `receiver_id` BIGINT NOT NULL COMMENT '接单方用户ID',
    MODIFY COLUMN `amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '成交金额',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 0 COMMENT '订单状态：0-待确认，1-进行中，2-已完成，3-已取消',
    MODIFY COLUMN `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态：0-待支付，1-已支付，2-已退款，3-已结算',
    MODIFY COLUMN `pay_gateway` VARCHAR(32) DEFAULT NULL COMMENT '支付网关：mock/wechat',
    MODIFY COLUMN `pay_no` VARCHAR(64) DEFAULT NULL COMMENT '支付流水号',
    MODIFY COLUMN `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
    MODIFY COLUMN `refund_time` DATETIME DEFAULT NULL COMMENT '退款时间',
    MODIFY COLUMN `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
    MODIFY COLUMN `confirm_time` DATETIME DEFAULT NULL COMMENT '确认时间',
    MODIFY COLUMN `finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
    MODIFY COLUMN `cancel_time` DATETIME DEFAULT NULL COMMENT '取消时间',
    MODIFY COLUMN `cancel_reason` VARCHAR(255) DEFAULT NULL COMMENT '取消原因',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='订单表';

ALTER TABLE `chat_session`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `session_type` TINYINT NOT NULL DEFAULT 1 COMMENT '会话类型：1-普通私聊，2-订单会话',
    MODIFY COLUMN `post_id` BIGINT DEFAULT NULL COMMENT '关联发布ID',
    MODIFY COLUMN `order_id` BIGINT DEFAULT NULL COMMENT '关联订单ID',
    MODIFY COLUMN `last_message_id` BIGINT DEFAULT NULL COMMENT '最后一条消息ID',
    MODIFY COLUMN `last_message_time` DATETIME DEFAULT NULL COMMENT '最后消息时间',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-关闭，1-正常',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='聊天会话表';

ALTER TABLE `chat_session_user`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `session_id` BIGINT NOT NULL COMMENT '会话ID',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN `last_read_message_id` BIGINT DEFAULT NULL COMMENT '最后已读消息ID',
    MODIFY COLUMN `last_read_time` DATETIME DEFAULT NULL COMMENT '最后已读时间',
    MODIFY COLUMN `unread_count` INT NOT NULL DEFAULT 0 COMMENT '未读数量',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='会话成员表';

ALTER TABLE `chat_message`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `session_id` BIGINT NOT NULL COMMENT '会话ID',
    MODIFY COLUMN `sender_id` BIGINT NOT NULL COMMENT '发送人ID',
    MODIFY COLUMN `message_type` TINYINT NOT NULL DEFAULT 1 COMMENT '消息类型：1-文本，2-图片，3-系统消息',
    MODIFY COLUMN `content` TEXT NOT NULL COMMENT '消息内容',
    MODIFY COLUMN `extra_json` JSON DEFAULT NULL COMMENT '扩展信息JSON',
    MODIFY COLUMN `is_recall` TINYINT NOT NULL DEFAULT 0 COMMENT '是否撤回：0-否，1-是',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT='聊天消息表';

ALTER TABLE `sys_module_item`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `module_name` VARCHAR(50) NOT NULL COMMENT '模块名称',
    MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '名称',
    MODIFY COLUMN `code` VARCHAR(100) NOT NULL COMMENT '编码',
    MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    MODIFY COLUMN `description` VARCHAR(255) DEFAULT NULL COMMENT '描述',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='通用模块数据表';

ALTER TABLE `sys_system_setting`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `platform_name` VARCHAR(100) NOT NULL COMMENT '平台名称',
    MODIFY COLUMN `support_email` VARCHAR(100) DEFAULT NULL COMMENT '支持邮箱',
    MODIFY COLUMN `service_phone` VARCHAR(50) DEFAULT NULL COMMENT '客服电话',
    MODIFY COLUMN `allow_register` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许注册：0-否，1-是',
    MODIFY COLUMN `maintenance_mode` TINYINT NOT NULL DEFAULT 0 COMMENT '维护模式：0-关闭，1-开启',
    MODIFY COLUMN `version` VARCHAR(50) DEFAULT NULL COMMENT '版本号',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='系统设置表';

ALTER TABLE `sys_user_profile`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN `real_name` VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    MODIFY COLUMN `gender` TINYINT NOT NULL DEFAULT 0 COMMENT '性别：0-未知，1-男，2-女',
    MODIFY COLUMN `birthday` DATE DEFAULT NULL COMMENT '生日',
    MODIFY COLUMN `city_name` VARCHAR(50) DEFAULT NULL COMMENT '城市',
    MODIFY COLUMN `area_name` VARCHAR(50) DEFAULT NULL COMMENT '区域',
    MODIFY COLUMN `address` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
    MODIFY COLUMN `bio` VARCHAR(500) DEFAULT NULL COMMENT '个人简介',
    MODIFY COLUMN `wallet_balance` DECIMAL(12, 2) NOT NULL DEFAULT 100000.00 COMMENT '钱包余额',
    MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT='用户扩展资料表';

